### ISSUE TITLE
Commercial events?

### ISSUE THREAD

**Issue by walterheck** [knode/node-meatspace#73]
I run a training company providing in-person classroom training in a part of the world where there currently is very little node.js training. Are commercial events like this welcome? 
Here's a list of upcoming locations: http://www.olindata.com/training/upcoming?technology=251

**Comment by hackygolucky** [comment]
Hrm. Interesting question. My assumption was that these are all community
run/related events. What line do we draw that at?

**Comment by evantahler** [comment]
Perhaps as long as they are free it is OK?

**Comment by mikeal** [comment]
Any event that is open to the public is valid.

**Comment by gergelyke** [comment]
How about introducing a new, 'Free' flag on the events (if they are free)? Something similar:
![meetspace_free](https://f.cloud.github.com/assets/2174968/1866277/1afb7076-782d-11e3-8f1d-a5325550832a.png)

**Comment by mikeal** [comment]
I don't think that quite captures the nuance we're trying to express. There are many events that don't make a profit, some that do, some that are bigger like conferences, some that are small like meetups, some that are hands-on like workshops. I'd like to stay away from encouraging any particular _type_ of event. The issue with tools like meetup is that they really push you in a specific direction in how an event is organized and presented. I'm more interested in experimentation and new formats like NodeSchool and NodeCopter but some of these are going to come with a cost (copters aint cheap) so, IMO, it would be better not to encourage any particular type or format.

**Comment by gergelyke** [comment]
Makes sense, I think, then all the public events are welcomed.

**Comment by walterheck** [comment]
I could see the benefit of having a price or something mentioned though? For instance our trainings are not cheap and if you are not interested in those kind of events why not know that before you click on them? So I'd propose something similar to what @gergelyke proposed, with the nuance that we mention price, not free/non-free. Would that be a good middle ground?

**Comment by rosskukulinski** [comment]
It gets tricky though when you get to conferences that have different
prices/packages.

**Comment by walterheck** [comment]
Couldn't that be solved by saying either "from 500USD" or "500/1500/2500 USD"? Keeping it simple at least..

**Comment by gergelyke** [comment]
I know, it is not easy to decide, but how about "for the profit"/"not for the profit" events?
Still not sure, if we should categorize them.

**Comment by hackygolucky** [comment]
I think displaying this much info(prices), for now at least, seems a bit
much. The linking allows for people to read more about the event they're
interested in.

**Comment by walterheck** [comment]
Ok, i'll submit a pull request with our trainings then. If people complain too much, we can always see how to move forward. My primary interest is in furthering the adoption of Node.JS (in our case through education) and doing so in a "proper" way, even though I also happen to make money off of the trainings.

**Comment by gergelyke** [comment]
Let's do this :)
